### ISSUE TITLE
Error while processing pow

### ISSUE THREAD

**Issue by tylerw1369** [SteppoFF/iota.keccak.pow.node.js#2]
I am getting this error when it's asked to process pow do you have any hints?
When I use George Athos iota-pow-benchmark it works fine but when I get pow sent to it from trinity app I get this error that pops up. 

22:59:12 - 2 Workers started
22:59:12 - Listening on port 19000                                                  TypeError: Cannot read property 'match' of undefined
    at /root/iota.keccak.pow.node.js/main.js:77:48
    at Layer.handle [as handle_request] (/root/iota.keccak.pow.node.js/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/iota.keccak.pow.node.js/node_modules/express/lib/router/index.js:317:13)
    at /root/iota.keccak.pow.node.js/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/iota.keccak.pow.node.js/node_modules/express/lib/router/index.js:335:12)
    at next (/root/iota.keccak.pow.node.js/node_modules/express/lib/router/index.js:275:10)
    at /root/iota.keccak.pow.node.js/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/root/iota.keccak.pow.node.js/node_modules/raw-body/index.js:224:16)
    at done (/root/iota.keccak.pow.node.js/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/root/iota.keccak.pow.node.js/node_modules/raw-body/index.js:273:7)

**Comment by tylerw1369** [comment]
it looks like it had to do with using my gneaubi build instead of gneaubihf.  got it fixed thanks for your help
